# Generated by Django 4.2 on 2023-12-04 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title of goal')),
                ('description', models.TextField(max_length=500, verbose_name='Description of goal')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date of goal creation')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Deadline of goal')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completion state of goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ('-creation_time',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title of task')),
                ('description', models.TextField(max_length=500, verbose_name='Description of task')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date of task creation')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Deadline of task')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completion state of task')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_tasks', to='main.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('-creation_time',),
            },
        ),
    ]
