# Generated by Django 4.2 on 2023-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_label_goal_image_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(null=True, related_name='task_labels', to='main.label'),
        ),
    ]
