# Generated by Django 4.2 on 2023-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'Github'), ('linkedin', 'Linkedin'), ('weibo', 'Weibo'), ('qq', 'Qq'), ('wechat', 'Wechat'), ('other', 'Other')], default='email', max_length=20, verbose_name='Login method'),
        ),
    ]
