# Generated by Django 4.2 on 2023-12-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_login_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
