# Generated by Django 4.2 on 2023-12-22 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When the goal should start'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When the task should start'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline of goal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline of task'),
        ),
    ]
