# Generated by Django 4.2 on 2023-12-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_goal_start_time_task_start_time_alter_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='prob_completion',
            field=models.FloatField(default=0.5, verbose_name='Ai probability of goal attainment'),
        ),
        migrations.AddField(
            model_name='task',
            name='prob_completion',
            field=models.FloatField(default=0.5, verbose_name='Ai prob of task completion'),
        ),
    ]
