# Generated by Django 4.2 on 2023-12-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_goal_prob_completion_task_prob_completion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('user', 'title')},
        ),
    ]
