# Generated by Django 4.2 on 2024-02-05 01:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_goal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
