# Generated by Django 4.2 on 2024-03-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired state of goal'),
        ),
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired state of task'),
        ),
    ]
